language: node_js

node_js:
  - 4.3

before_script:
  - npm run-script danger

script:
  - make coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

email: false
